services:
  vaultwarden:
    image: vaultwarden/server:1.37.2
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "https://vw.tamvo.dpdns.org"
    volumes:
      - /vw-data/:/data/
