services:
  vaultwarden:
    image: vaultwarden/server:1.37.3
    container_name: vaultwarden
    labels:
      service: vaultwarden
    logging:
      driver: json-file
      options:
        labels: service
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:80"
    environment:
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "https://vw.tamvo.dpdns.org"
    volumes:
      - /vw-data/:/data/
